# Feature Engineering for Profit Prediction

Now we prepare the dataset for machine learning by creating new features and transforming categorical variables.

Goal: Construct a dataset suitable for predicting profit and optimizing discount strategies.

## Importing Libraries

In [4]:
import pandas as pd
import numpy as np

## Load Dataset

In [5]:
df = pd.read_csv("../data/raw/superstore.csv", encoding="latin1")

## Conversion Of Date Columns

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

## Create Time Features

In [9]:
df['Shipping Time'] = (df['Ship Date'] - df['Order Date']).dt.days
df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year
df["Day Of Week"] = df["Order Date"].dt.dayofweek

## Pricing Features

In [11]:
df["Item Price"] = df["Sales"] / df["Quantity"]

In [12]:
df["Profit Margin"] = df["Profit"] / df["Sales"]

## Order Size Features

In [14]:
df["Value Per Item"] = df["Sales"] / df["Quantity"]

In [15]:
df["Discount Amount"] = df["Sales"] * df["Discount"]

## Feature Selection

In [17]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Shipping Time,Month,Year,Day Of Week,Unit Price,Item Price,Profit Margin,Value Per Item,Discount Amount
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,55190.379428,229.858001,3.789574,0.156203,28.656896,3.958175,7.809686,2015.722233,3.206324,60.919569,60.919569,0.120314,60.919569,32.277580
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000,1.000000,2014.000000,0.000000,0.336000,0.336000,-2.750000,0.336000,0.000000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,3.000000,5.000000,2015.000000,1.000000,5.470000,5.470000,0.075000,5.470000,0.000000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,4.000000,9.000000,2016.000000,4.000000,16.270000,16.270000,0.270000,16.270000,1.036800
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,5.000000,11.000000,2017.000000,5.000000,63.940000,63.940000,0.362500,63.940000,14.870400
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,7.000000,12.000000,2017.000000,6.000000,3773.080000,3773.080000,0.500000,3773.080000,11319.240000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.747567,3.284654,1.123555,2.122925,142.927440,142.927440,0.466754,142.927440,164.025577

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Row ID           9994 non-null   int64
 1   Order ID         9994 non-null   str
 2   Order Date       9994 non-null   datetime64[us]
 3   Ship Date        9994 non-null   datetime64[us]
 4   Ship Mode        9994 non-null   str
 5   Customer ID      9994 non-null   str
 6   Customer Name    9994 non-null   str
 7   Segment          9994 non-null   str
 8   Country          9994 non-null   str
 9   City             9994 non-null   str
 10  State            9994 non-null   str
 11  Postal Code      9994 non-null   int64
 12  Region           9994 non-null   str
 13  Product ID       9994 non-null   str
 14  Category         9994 non-null   str
 15  Sub-Category     9994 non-null   str
 16  Product Name     9994 non-null   str
 17  Sales            9994 non-null   float64
 18  Quantity         9994 non-null   int64
 19  Discount         9994 non-null   float64
 20  Profit           9994 non-null   float64
 21  Shipping Time    9994 non-null   int64
 22  Month            9994 non-null   int32
 23  Year             9994 non-null   int32
 24  Day Of Week      9994 non-null   int32
 25  Unit Price       9994 non-null   float64
 26  Item Price       9994 non-null   float64
 27  Profit Margin    9994 non-null   float64
 28  Value Per Item   9994 non-null   float64
 29  Discount Amount  9994 non-null   float64
dtypes: datetime64[us](2), float64(8), int32(3), int64(4), str(13)
memory usage: 2.2 MB

In [19]:
features = [
    "Sales",
    "Quantity",
    "Discount",
    "Shipping Time",
    "Month",
    "Year",
    "Day Of Week",
    "Unit Price",
    "Item Price",
    "Value Per Item",
    "Discount Amount",
    "Ship Mode",
    "Segment",
    "Category",
    "Sub-Category",
    "Region"
]

target = "Profit"

In [20]:
df_model = df[features + [target]].copy()

In [21]:
df_model.head()

,Sales,Quantity,Discount,Shipping Time,Month,Year,Day Of Week,Unit Price,Item Price,Value Per Item,Discount Amount,Ship Mode,Segment,Category,Sub-Category,Region,Profit
0,261.9600,2,0.00,3,11,2016,1,130.9800,130.9800,130.9800,0.000000,Second Class,Consumer,Furniture,Bookcases,South,41.9136
1,731.9400,3,0.00,3,11,2016,1,243.9800,243.9800,243.9800,0.000000,Second Class,Consumer,Furniture,Chairs,South,219.5820
2,14.6200,2,0.00,4,6,2016,6,7.3100,7.3100,7.3100,0.000000,Second Class,Corporate,Office Supplies,Labels,West,6.8714
3,957.5775,5,0.45,7,10,2015,6,191.5155,191.5155,191.5155,430.909875,Standard Class,Consumer,Furniture,Tables,South,-383.0310
4,22.3680,2,0.20,7,10,2015,6,11.1840,11.1840,11.1840,4.473600,Standard Class,Consumer,Office Supplies,Storage,South,2.5164

In [23]:
df_model.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sales            9994 non-null   float64
 1   Quantity         9994 non-null   int64
 2   Discount         9994 non-null   float64
 3   Shipping Time    9994 non-null   int64
 4   Month            9994 non-null   int32
 5   Year             9994 non-null   int32
 6   Day Of Week      9994 non-null   int32
 7   Unit Price       9994 non-null   float64
 8   Item Price       9994 non-null   float64
 9   Value Per Item   9994 non-null   float64
 10  Discount Amount  9994 non-null   float64
 11  Ship Mode        9994 non-null   str
 12  Segment          9994 non-null   str
 13  Category         9994 non-null   str
 14  Sub-Category     9994 non-null   str
 15  Region           9994 non-null   str
 16  Profit           9994 non-null   float64
dtypes: float64(7), int32(3), int64(2), str(5)
memory usage: 1.2 MB